name: Deploy to Domainesia

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: digiflazz.enuyrasa.my.id
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/
          state-name: .ftp-deploy-sync-state.json
          exclude: |
            **/.git/**
            **/.git
            **/node_modules/**
            README-deploy.md
            *.xlsx
            *.csv
            .github/**
            .ftp-deploy-sync-state.json
